# Generated by Django 4.1.7 on 2023-02-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("thumb_img", models.ImageField(upload_to="")),
                ("desc", models.TextField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("thumb_img", models.ImageField(blank=True, upload_to="")),
                ("desc", models.TextField()),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("availability", models.BooleanField(default=False)),
                ("genre", models.ManyToManyField(blank=True, to="LMS.genre")),
            ],
        ),
    ]
