# Generated by Django 4.1.7 on 2023-02-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LMS", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("desc", models.TextField()),
                ("image", models.ImageField(upload_to="author-images/")),
            ],
        ),
        migrations.AlterField(
            model_name="book",
            name="thumb_img",
            field=models.ImageField(blank=True, upload_to="book-img/"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="thumb_img",
            field=models.ImageField(blank=True, upload_to="genre-img/"),
        ),
    ]
