# Generated by Django 4.1.7 on 2023-02-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LMS", "0003_author_alter_book_thumb_img_alter_genre_thumb_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="LMS.author",
            ),
        ),
    ]
