# Generated by Django 4.1.7 on 2023-02-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LMS", "0006_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ImageField(blank=True, upload_to="author-images/"),
        ),
    ]
