# Generated by Django 4.1.7 on 2023-02-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LMS", "0008_alter_book_author_alter_book_issued_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
