# Generated by Django 4.1.7 on 2023-02-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LMS", "0010_alter_author_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
