# Generated by Django 4.1.7 on 2023-02-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LMS", "0011_alter_author_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="desc",
            field=models.TextField(max_length=400),
        ),
    ]
