# Generated by Django 4.1.7 on 2023-03-01 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("LMS", "0012_alter_genre_desc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
        migrations.AddField(
            model_name="book",
            name="Genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="LMS.genre",
            ),
        ),
    ]
