# Generated by Django 4.1.7 on 2023-03-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LMS", "0016_rename_orders_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="returned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
