# Generated by Django 4.1.7 on 2023-03-02 09:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LMS", "0017_order_returned_date_alter_order_order_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="returned_date",
            new_name="return_date",
        ),
    ]
