# Generated by Django 4.1.7 on 2023-02-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_student_date_joined_student_is_active_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="Name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="student",
            name="image",
            field=models.ImageField(blank=True, default="", upload_to="user/images/"),
        ),
        migrations.AlterField(
            model_name="student",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
