# Generated by Django 4.1.7 on 2023-02-23 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0003_rename_name_student_name_alter_student_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"permissions": [("view_author", "Can view author")]},
        ),
    ]
