# Generated by Django 4.1.7 on 2023-02-25 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_student_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={},
        ),
    ]
